name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn package

      - name: Build Docker Image
        run: |
          RUN_NUMBER=${{ github.run_number }}
          docker build --build-arg VAR=${RUN_NUMBER} -t emanuel115/maven-app:1.0.${RUN_NUMBER} .
      
      - name: Push to Docker Hub
        run: |
          RUN_NUMBER=${{ github.run_number }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push emanuel115/maven-app:1.0.${RUN_NUMBER}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 400 ~/.ssh/deploy_key.pem

      - name: Deploy to EC2
        run: |
          RUN_NUMBER=${{ github.run_number }}
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key.pem ubuntu@13.60.40.19 << 'EOF'
            docker pull emanuel115/maven-app:1.0.${RUN_NUMBER}
            docker run -d --name maven-app -p 8080:8080 emanuel115/maven-app:1.0.${RUN_NUMBER}
          EOF
