name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn package

      - name: Build Docker Image
        run: |
          RUN_NUMBER=${{ github.run_number }}
          docker build -t emanuel115/maven-app:1.0.${RUN_NUMBER} .
      
      - name: Push to Docker Hub
        run: |
          RUN_NUMBER=${{ github.run_number }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push emanuel115/maven-app:1.0.${RUN_NUMBER}
